contentCrs:
  name: Content-Crs
  in: header
  required: false
  description: CRS van de meegegeven geometrie
  schema:
    type: string
    enum:
      - 'epsg:4326'
      - 'epsg:28992'
    default: 'epsg:4326'
acceptCrs:
  name: Accept-Crs
  in: header
  required: false
  description: Gewenste CRS van de coördinaten in de response
  schema:
    type: string
    enum:
      - 'epsg:4326'
      - 'epsg:28992'
    default: 'epsg:4326'
page:
  description: Pagina nummer
  name: page
  in: query
  required: false
  schema:
    type: integer
    minimum: 1
    default: 1
pageSize:
  name: pageSize
  in: query
  required: false
  schema:
    type: integer
    enum:
      - 10
      - 20
      - 50
      - 100
    default: 20
