contentCrs:
  name: Content-Crs
  in: header
  required: false
  description: CRS van de meegegeven geometrie
  schema:
    type: string
    enum:
      - 'epsg:4326'
      - 'epsg:28992'
    default: 'epsg:4326'
acceptCrs:
  name: Accept-Crs
  in: header
  required: false
  description: Gewenste CRS van de coördinaten in de response
  schema:
    type: string
    enum:
      - 'epsg:4326'
      - 'epsg:28992'
    default: 'epsg:4326'
page:
  name: page
  in: query
  description: Page number
  required: false
  schema:
    type: integer
    minimum: 1
    default: 1